// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIDFow2SaAjwF4KmDn8wfXhbmcp7dfTnE',
    appId: '1:1043862444872:web:18f5d77fc8244ec3ea717d',
    messagingSenderId: '1043862444872',
    projectId: 'todo-app-e5f07',
    authDomain: 'todo-app-e5f07.firebaseapp.com',
    storageBucket: 'todo-app-e5f07.appspot.com',
    measurementId: 'G-1P7PJ8MTQ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC1I51fO8RS0wsOhzzI8mjoqNUP0Jr-2o',
    appId: '1:1043862444872:android:cca901473371c6e3ea717d',
    messagingSenderId: '1043862444872',
    projectId: 'todo-app-e5f07',
    storageBucket: 'todo-app-e5f07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-H9YZ4BptZ1KyINMzerOrPOWElcWgXUA',
    appId: '1:1043862444872:ios:5c97f530cf9fe9faea717d',
    messagingSenderId: '1043862444872',
    projectId: 'todo-app-e5f07',
    storageBucket: 'todo-app-e5f07.appspot.com',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-H9YZ4BptZ1KyINMzerOrPOWElcWgXUA',
    appId: '1:1043862444872:ios:bfef054e6a9ece7eea717d',
    messagingSenderId: '1043862444872',
    projectId: 'todo-app-e5f07',
    storageBucket: 'todo-app-e5f07.appspot.com',
    iosBundleId: 'com.example.todoapp.RunnerTests',
  );
}
